'use client';

import { useState, useEffect, useRef } from 'react';
import { PersonalizedInsight } from '@/types/insights';
import InsightsCharts from './InsightsCharts';
import AlizaMessages from '../journal/AlizaMessages';
import { supabase } from '@/lib/supabase';
import { useTokens } from '@/hooks/useTokens';
import './AlizaInsights.css';

interface AlizaInsightsProps {
  userId: string;
}

export default function AlizaInsights({ userId }: AlizaInsightsProps) {
  const [insights, setInsights] = useState<PersonalizedInsight[]>([]);
  const [heroInsight, setHeroInsight] = useState<PersonalizedInsight | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedInsight, setSelectedInsight] = useState<PersonalizedInsight | null>(null);
  const [timeRange, setTimeRange] = useState<'week' | 'month' | 'quarter'>('month');
  const [dailyEntries, setDailyEntries] = useState<any[]>([]);
  const [cycleEntries, setCycleEntries] = useState<any[]>([]);
  const [userName, setUserName] = useState<string>('יקרה');
  const [hasData, setHasData] = useState<boolean>(false);
  const [insightsRawData, setInsightsRawData] = useState<any[]>([]); // Store raw database data for sorting
  const { loadTokens } = useTokens();

  useEffect(() => {
    if (userId) {
      loadEntries();
      loadUserName();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId]);

  const loadUserName = async () => {
    try {
      const { data: profile } = await supabase
        .from('user_profile')
        .select('first_name, name, full_name, email')
        .eq('id', userId)
        .single();
      
      if (profile) {
        // Use first_name only for display
        const name = profile.first_name || profile.name?.split(' ')[0] || profile.full_name?.split(' ')[0] || profile.email?.split('@')[0] || 'יקרה';
        setUserName(name);
      }
    } catch (error) {
      console.error('Error loading user name:', error);
    }
  };

  // Load insights after entries are loaded
  useEffect(() => {
    if (userId && (dailyEntries.length > 0 || cycleEntries.length > 0)) {
      // Load insights from database (generated by daily cron job)
      loadInsights();
    } else if (userId) {
      // Even if no entries, try to load existing insights
      loadInsights();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId, dailyEntries.length, cycleEntries.length]);

  const loadEntries = async () => {
    try {
      console.log('📊 Loading entries for user:', userId);
      const [dailyResult, cycleResult] = await Promise.all([
        supabase.from('daily_entries').select('*').eq('user_id', userId).order('date', { ascending: false }),
        supabase.from('cycle_entries').select('*').eq('user_id', userId).order('date', { ascending: false })
      ]);
      
      if (dailyResult.error) {
        console.error('❌ Error loading daily entries:', dailyResult.error);
      } else {
        console.log('✅ Loaded daily entries:', dailyResult.data?.length || 0);
      }
      
      if (cycleResult.error) {
        console.error('❌ Error loading cycle entries:', cycleResult.error);
      } else {
        console.log('✅ Loaded cycle entries:', cycleResult.data?.length || 0);
      }
      
      const daily = dailyResult.data || [];
      const cycle = cycleResult.data || [];
      
      setDailyEntries(daily);
      setCycleEntries(cycle);
      
      // Check if user has any data
      const hasAnyData = daily.length > 0 || cycle.length > 0;
      setHasData(hasAnyData);
      
      console.log('📊 Entries loaded:', {
        daily: daily.length,
        cycle: cycle.length,
        hasData: hasAnyData
      });
    } catch (error) {
      console.error('❌ Error loading entries:', error);
    }
  };

  const loadInsights = async () => {
    setIsLoading(true);
    try {
      console.log('🔍 Loading insights from database for user:', userId);
      
      // Check if this is a mock user
      if (userId.startsWith('mock-user-')) {
        console.log('Insights: Using mock data for mock user');
        // Generate mock insights for demo
        const mockInsights: PersonalizedInsight[] = [
          {
            id: 'mock-1',
            type: 'pattern',
            title: 'דפוסי שינה משופרים',
            content: 'זיהיתי דפוס של שינה טובה יותר בימים שבהם את עושה פעילות גופנית.',
            priority: 'medium',
            category: 'sleep',
            actionable: true,
            relatedData: {},
            alizaMessage: 'זה נהדר! אני רואה שכשאת עושה פעילות גופנית, את ישנה טוב יותר. זה בדיוק מה שהמחקרים מראים - פעילות גופנית עוזרת לווסת את ההורמונים ולשפר את איכות השינה.'
          },
          {
            id: 'mock-2',
            type: 'encouragement',
            title: 'את עושה עבודה נהדרת!',
            content: 'אני רואה שיש שיפור במצב הרוח שלך בשבוע האחרון.',
            priority: 'low',
            category: 'mood',
            actionable: false,
            relatedData: {},
            alizaMessage: 'זה נהדר! אני רואה שיש שיפור במצב הרוח שלך. זה מראה שהגוף שלך מתחיל להסתגל לשינויים. המשכי עם מה שעובד בשבילך!'
          }
        ];
        
        setInsights(mockInsights);
        setIsLoading(false);
        return;
      }
      
      // Load insights from database - load ALL insights (not just today's)
      // This preserves old insights when new ones are created
      console.log('🔍 Loading all insights for user:', userId);
      
      // Get current auth user to verify RLS
      const { data: { user: authUser } } = await supabase.auth.getUser();
      console.log('👤 Auth user:', {
        id: authUser?.id,
        email: authUser?.email,
        matchesUserId: authUser?.id === userId
      });
      
      // Load ALL insights for this user, ordered by date (newest first) and priority
      let { data: insightsData, error: insightsError } = await supabase
        .from('personalized_insights')
        .select('*')
        .eq('user_id', userId)
        .order('analysis_date', { ascending: false })
        .order('priority', { ascending: false })
        .order('created_at', { ascending: false })
        .limit(50); // Limit to 50 most recent insights

      console.log('📊 All insights loaded:', {
        count: insightsData?.length || 0,
        error: insightsError,
        dates: insightsData?.map(i => i.analysis_date) || []
      });

      if (insightsError) {
        console.error('❌ Error loading insights from database:', insightsError);
        console.error('❌ Error details:', JSON.stringify(insightsError, null, 2));
        setInsights([]);
        setHeroInsight(null);
        setIsLoading(false);
        return;
      }

      // If no insights found, check if user has data
      if (!insightsData || insightsData.length === 0) {
        console.log('⚠️ No insights found in database.');
        
        // Check if user has data by querying database directly
        const [dailyCheck, cycleCheck] = await Promise.all([
          supabase.from('daily_entries').select('id', { count: 'exact', head: true }).eq('user_id', userId),
          supabase.from('cycle_entries').select('id', { count: 'exact', head: true }).eq('user_id', userId)
        ]);
        
        const hasAnyData = (dailyCheck.count || 0) > 0 || (cycleCheck.count || 0) > 0;
        setHasData(hasAnyData);
        if (hasAnyData) {
          console.log('✅ User has data, will show generate button');
        } else {
          console.log('⚠️ No data available for user');
        }
      }

      if (!insightsData || insightsData.length === 0) {
        console.log('⚠️ No insights found in database. Insights will be generated by the daily cron job or can be generated manually.');
        setInsights([]);
        setHeroInsight(null);
        setIsLoading(false);
        return;
      }

      // Store raw data for sorting later
      setInsightsRawData(insightsData);

      // Convert database format to PersonalizedInsight format
      const loadedInsights: PersonalizedInsight[] = insightsData.map((insight: any) => ({
        id: insight.insight_id,
        type: insight.type,
        title: insight.title,
        content: insight.content,
        priority: insight.priority,
        category: insight.category,
        actionable: insight.actionable || false,
        comparisonToNorm: insight.comparison_to_norm,
        actionableSteps: insight.actionable_steps,
        visualData: insight.visual_data,
        alizaMessage: insight.aliza_message || '',
        relatedData: {}
      }));

      console.log('✅ Loaded insights from database:', loadedInsights.length);
      console.log('📋 Insights details:', loadedInsights.map(i => ({ 
        id: i.id, 
        title: i.title, 
        priority: i.priority,
        analysisDate: insightsData.find((db: any) => db.insight_id === i.id)?.analysis_date
      })));
      
      // זיהוי תובנת Hero - התובנה הכי חשובה (עדיפות גבוהה עם השוואה לנורמה, או עדיפות גבוהה, או עם השוואה)
      // אבל נבחר את התובנה החדשה ביותר (האחרונה) כ-Hero, לא את הראשונה
      const sortedByDate = [...loadedInsights].sort((a, b) => {
        const aDate = insightsData.find((db: any) => db.insight_id === a.id)?.created_at || '';
        const bDate = insightsData.find((db: any) => db.insight_id === b.id)?.created_at || '';
        return bDate.localeCompare(aDate); // Newest first
      });
      
      const hero = sortedByDate.length > 0 
        ? (sortedByDate.find(i => i.priority === 'high' && i.comparisonToNorm) 
          || sortedByDate.find(i => i.priority === 'high')
          || sortedByDate.find(i => i.comparisonToNorm)
          || sortedByDate[0]) // Take the newest one
        : null;
      
      console.log('🎯 Selected Hero insight:', hero ? { id: hero.id, title: hero.title } : 'none');
      
      setHeroInsight(hero || null);
      // נציג את כל התובנות, כולל את ה-Hero (הוא יוצג גם בנפרד כ-Hero וגם ברשימה)
      // כך המשתמשת תראה את כל התובנות שנוצרו
      console.log('📊 Setting insights state:', {
        hero: hero ? hero.id : null,
        totalInsights: loadedInsights.length,
        allInsightsIncluded: true
      });
      // נציג את כל התובנות, לא רק את השאר
      setInsights(loadedInsights);
    } catch (error) {
      console.error('❌ Error loading insights:', error);
      setInsights([]);
      setHeroInsight(null);
    } finally {
      setIsLoading(false);
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return '#ff6b6b';
      case 'medium': return '#f9ca24';
      case 'low': return '#4ecdc4';
      default: return '#6c757d';
    }
  };

  const getCategoryIcon = (category: string) => {
    const icons: Record<string, string> = {
      sleep: '😴',
      mood: '😊',
      symptoms: '🌡️',
      hormones: '⚡',
      lifestyle: '🏃‍♀️',
      cycle: '🌸',
      general: '💡'
    };
    return icons[category] || '💡';
  };

  const getTypeIcon = (type: string) => {
    const icons: Record<string, string> = {
      pattern: '📊',
      recommendation: '💡',
      warning: '⚠️',
      encouragement: '🎉'
    };
    return icons[type] || '💡';
  };

  if (isLoading) {
    return (
      <div className="aliza-insights-loading">
        <div className="loading-container">
          <div className="aliza-avatar">
            <img src="/aliza_profile.jpg" alt="עליזה" />
          </div>
          <div className="loading-spinner"></div>
          <h3>עליזה מנתחת את הנתונים שלך...</h3>
          <p>זה יכול לקחת כמה רגעים</p>
        </div>
      </div>
    );
  }

  return (
    <div className="aliza-insights">
      {/* Header with Aliza */}
      <div className="aliza-header">
        <div className="aliza-avatar-large">
          <img src="/aliza_profile.jpg" alt="עליזה - החברה והדולה שלך למסע" />
        </div>
        <div className="aliza-intro">
          <h2>שלום! אני עליזה, החברה והדולה שלך למסע</h2>
          <p>אני מנופאוזית מנוסה שעברה בעצמי את כל מה שאת עוברת. אחרי שנים של מחקר וחוויה, ניתחתי את הנתונים שהכנסת ויש לי כמה תובנות מעניינות לשתף איתך על המסע שלך</p>
        </div>
      </div>

      {/* Hero Insight - התובנה המרכזית החשובה ביותר */}
      {heroInsight && (
        <div className="hero-insight-section">
          <div className="hero-insight-card" onClick={() => setSelectedInsight(heroInsight)}>
            <div className="hero-insight-header">
              <div className="hero-insight-badge">
                <span className="hero-badge-icon">⭐</span>
                <span className="hero-badge-text">התובנה החשובה ביותר עבורך</span>
              </div>
              <div className="hero-insight-priority" style={{ backgroundColor: getPriorityColor(heroInsight.priority) }}>
                {heroInsight.priority === 'high' ? 'גבוהה' : heroInsight.priority === 'medium' ? 'בינונית' : 'נמוכה'}
              </div>
            </div>
            
            <div className="hero-insight-content">
              <div className="hero-insight-icon">
                <span>{getCategoryIcon(heroInsight.category)}</span>
              </div>
              <div className="hero-insight-main">
                <h3 className="hero-insight-title">{heroInsight.title}</h3>
                <p className="hero-insight-description">{heroInsight.content}</p>
                
                {heroInsight.comparisonToNorm && (
                  <div className="hero-comparison">
                    <div className="hero-comparison-bar">
                      <div className="comparison-item">
                        <span className="comparison-label">{userName}:</span>
                        <div className="comparison-value-bar">
                          <div 
                            className="comparison-fill user-fill"
                            style={{ width: `${Math.min(heroInsight.comparisonToNorm.userValue, 100)}%` }}
                          >
                            <span className="comparison-number">{Math.round(heroInsight.comparisonToNorm.userValue)}%</span>
                          </div>
                        </div>
                      </div>
                      <div className="comparison-item">
                        <span className="comparison-label">ממוצע:</span>
                        <div className="comparison-value-bar">
                          <div 
                            className="comparison-fill average-fill"
                            style={{ width: `${Math.min(heroInsight.comparisonToNorm.averageValue, 100)}%` }}
                          >
                            <span className="comparison-number">{Math.round(heroInsight.comparisonToNorm.averageValue)}%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                    <p className="hero-comparison-explanation">{heroInsight.comparisonToNorm.explanation}</p>
                  </div>
                )}
                
                <div className="hero-aliza-message">
                  <div className="hero-aliza-header">
                    <div className="hero-aliza-avatar">
                      <img src="/aliza_profile.jpg" alt="עליזה" />
                    </div>
                    <span className="hero-aliza-name">עליזה אומרת:</span>
                  </div>
                  <p className="hero-aliza-text">{heroInsight.alizaMessage}</p>
                </div>
              </div>
            </div>
            
            {heroInsight.actionable && (
              <div className="hero-actionable">
                <span className="hero-actionable-icon">💡</span>
                <span>יש לך פעולות מעשיות שתוכלי לבצע - לחצי לפרטים</span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Charts Section */}
      <InsightsCharts 
        dailyEntries={dailyEntries}
        cycleEntries={cycleEntries}
        timeRange={timeRange}
        onTimeRangeChange={setTimeRange}
      />

      {/* Insights Grid */}
      <div className="insights-section">
        <div className="section-header">
          <h3>💡 התובנות שלי עבורך</h3>
          <p>ניתוח אישי של הנתונים שלך</p>
        </div>

        <div className="insights-grid">
          {insights.length === 0 && !heroInsight ? (
            <div className="no-insights-state">
              <div className="no-insights-icon">💡</div>
              <h4>עדיין אין תובנות</h4>
              <p>
                {!hasData 
                  ? 'כשתתחילי להזין רשומות יומן ומעקב מחזור, עליזה תוכל לנתח את הנתונים שלך ולספק תובנות אישיות.'
                  : 'עליזה מעבדת את הנתונים שלך. תובנות חדשות יופיעו כאן בקרוב.'}
              </p>
              {hasData && (
                <div className="generate-insights-action">
                  <button 
                    className="generate-insights-button"
                    onClick={async () => {
                      setIsLoading(true);
                      try {
                        console.log('🔄 Generating insights manually...');
                        // Call API to generate and save insights
                        const response = await fetch('/api/generate-insights-now', {
                          method: 'POST',
                          headers: {
                            'Content-Type': 'application/json',
                          },
                          body: JSON.stringify({ userId }),
                        });

                        if (!response.ok) {
                          const errorData = await response.json();
                          console.error('❌ API error:', errorData);
                          throw new Error(errorData.error || 'Failed to generate insights');
                        }

                        const result = await response.json();
                        console.log('✅ Insights generated:', result);

                        // Update tokens in real-time if tokens were deducted
                        if (result.deduct_tokens && result.deduct_tokens > 0) {
                          console.log('🔄 Updating tokens after insights generation:', result.deduct_tokens);
                          // Wait a bit for database to update
                          await new Promise(resolve => setTimeout(resolve, 300));
                          // Reload tokens to get the updated value from database
                          await loadTokens();
                        }

                        // Wait a bit to ensure data is saved to database
                        await new Promise(resolve => setTimeout(resolve, 500));

                        // Reload insights from database
                        console.log('🔄 Reloading insights from database...');
                        await loadInsights();
                        console.log('✅ Insights reloaded');
                      } catch (error) {
                        console.error('❌ Error generating insights:', error);
                        alert('שגיאה ביצירת תובנות. נסי שוב מאוחר יותר.');
                      } finally {
                        setIsLoading(false);
                      }
                    }}
                    disabled={isLoading}
                  >
                    {isLoading ? 'יוצר תובנות...' : 'יצירת תובנות עכשיו'}
                  </button>
                  <p className="generate-hint">
                    התובנות נוצרות אוטומטית פעם ביום בבוקר. לחיצה כאן תיצור תובנות חדשות עכשיו על בסיס כל הנתונים שלך.
                  </p>
                </div>
              )}
            </div>
          ) : (
            // הצג את כל התובנות, מסודרות לפי תאריך (החדשות ביותר קודם)
            insights
              .sort((a, b) => {
                // מצא את התאריך של כל תובנה מהנתונים המקוריים
                const aDate = insightsRawData.find((db: any) => db.insight_id === a.id)?.created_at || '';
                const bDate = insightsRawData.find((db: any) => db.insight_id === b.id)?.created_at || '';
                return bDate.localeCompare(aDate); // Newest first
              })
              .map((insight) => {
                // מצא את התאריך האמיתי של התובנה מהנתונים המקוריים
                const rawInsight = insightsRawData.find((db: any) => db.insight_id === insight.id);
                const insightDate = rawInsight?.analysis_date || rawInsight?.created_at || new Date().toISOString().split('T')[0];
                
                return (
              <div 
                key={insight.id} 
                className={`insight-card ${insight.priority}`}
                onClick={() => setSelectedInsight(insight)}
              >
                <div className="insight-header">
                  <div className="insight-icons">
                    <span className="category-icon">{getCategoryIcon(insight.category)}</span>
                    <span className="type-icon">{getTypeIcon(insight.type)}</span>
                  </div>
                  <div className="insight-priority" style={{ backgroundColor: getPriorityColor(insight.priority) }}>
                    {insight.priority === 'high' ? 'גבוהה' : insight.priority === 'medium' ? 'בינונית' : 'נמוכה'}
                  </div>
                </div>
                
                <div className="insight-content">
                  <h4 className="insight-title">{insight.title}</h4>
                  <p className="insight-description">{insight.content}</p>
                  
                  {insight.actionable && (
                    <div className="actionable-badge">
                      <span>💡 ניתן לפעולה</span>
                    </div>
                  )}
                </div>

                <div className="insight-footer">
                  <span className="insight-category">{insight.category}</span>
                  <span className="insight-date">
                    {new Date(insightDate).toLocaleDateString('he-IL')}
                  </span>
                </div>
              </div>
            );
            })
          )}
        </div>
      </div>

      {/* Aliza's Messages Section */}
      <div className="aliza-messages-section">
        <AlizaMessages 
          userId={userId}
          dailyEntries={dailyEntries}
          cycleEntries={cycleEntries}
        />
      </div>

      {/* Insight Detail Modal */}
      {selectedInsight && (
        <div className="insight-modal-overlay" onClick={() => setSelectedInsight(null)}>
          <div className="insight-modal-container" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>{selectedInsight.title}</h3>
              <button 
                className="close-button"
                onClick={() => setSelectedInsight(null)}
              >
                ✕
              </button>
            </div>
            
            <div className="insight-modal-content">
              <div className="modal-content">
                <div className="insight-details">
                  <div className="detail-row">
                    <span className="detail-label">קטגוריה:</span>
                    <span className="detail-value">{selectedInsight.category}</span>
                  </div>
                  <div className="detail-row">
                    <span className="detail-label">עדיפות:</span>
                    <span className="detail-value" style={{ color: getPriorityColor(selectedInsight.priority) }}>
                      {selectedInsight.priority === 'high' ? 'גבוהה' : selectedInsight.priority === 'medium' ? 'בינונית' : 'נמוכה'}
                    </span>
                  </div>
                  <div className="detail-row">
                    <span className="detail-label">סוג:</span>
                    <span className="detail-value">{selectedInsight.type}</span>
                  </div>
                </div>

              {/* השוואה לנורמה */}
              {selectedInsight.comparisonToNorm && (
                <div className="comparison-section">
                  <h4>📊 השוואה לנורמה</h4>
                  <div className="comparison-content">
                    <div className="comparison-bar">
                      <div className="comparison-label">
                        <span>{userName}:</span>
                        <span className="comparison-value">{Math.round(selectedInsight.comparisonToNorm.userValue)}%</span>
                      </div>
                      <div className="comparison-bar-container">
                        <div 
                          className="comparison-bar-fill user-bar"
                          style={{ width: `${Math.min(selectedInsight.comparisonToNorm.userValue, 100)}%` }}
                        />
                      </div>
                    </div>
                    <div className="comparison-bar">
                      <div className="comparison-label">
                        <span>ממוצע:</span>
                        <span className="comparison-value">{Math.round(selectedInsight.comparisonToNorm.averageValue)}%</span>
                      </div>
                      <div className="comparison-bar-container">
                        <div 
                          className="comparison-bar-fill average-bar"
                          style={{ width: `${Math.min(selectedInsight.comparisonToNorm.averageValue, 100)}%` }}
                        />
                      </div>
                    </div>
                    <p className="comparison-explanation">{selectedInsight.comparisonToNorm.explanation}</p>
                  </div>
                </div>
              )}

              <div className="insight-description-full">
                <h4>תיאור מפורט:</h4>
                <p>{selectedInsight.content}</p>
              </div>

              {/* גרף ויזואלי */}
              {selectedInsight.visualData && (
                <div className="visual-data-section">
                  <h4>📈 המחשה גרפית</h4>
                  <div className="simple-chart-container">
                    <SimpleChart 
                      data={selectedInsight.visualData.data}
                      type={selectedInsight.visualData.chartType}
                      color={getPriorityColor(selectedInsight.priority)}
                    />
                  </div>
                </div>
              )}

              <div className="aliza-message-detail">
                <div className="message-header">
                  <h4>עליזה אומרת:</h4>
                  <div className="aliza-avatar-small">
                    <img src="/aliza_profile.jpg" alt="עליזה" />
                  </div>
                </div>
                <p>{selectedInsight.alizaMessage}</p>
              </div>

              {selectedInsight.actionable && selectedInsight.actionableSteps && (
                <div className="actionable-section">
                  {selectedInsight.actionableSteps.reliefMethods && selectedInsight.actionableSteps.reliefMethods.length > 0 && (
                    <div className="actionable-subsection">
                      <h4>
                        <span>💡</span>
                        <span>דרכים להקל על התסמינים:</span>
                      </h4>
                      <ul>
                        {selectedInsight.actionableSteps.reliefMethods.map((method, index) => (
                          <li key={index}>{method}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {selectedInsight.actionableSteps.whoToContact && selectedInsight.actionableSteps.whoToContact.length > 0 && (
                    <div className="actionable-subsection">
                      <h4>
                        <span>👩‍⚕️</span>
                        <span>למי כדאי לפנות:</span>
                      </h4>
                      <ul>
                        {selectedInsight.actionableSteps.whoToContact.map((contact, index) => (
                          <li key={index}>{contact}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {selectedInsight.actionableSteps.questionsToAsk && selectedInsight.actionableSteps.questionsToAsk.length > 0 && (
                    <div className="actionable-subsection">
                      <h4>
                        <span>❓</span>
                        <span>שאלות חשובות לשאול:</span>
                      </h4>
                      <ul>
                        {selectedInsight.actionableSteps.questionsToAsk.map((question, index) => (
                          <li key={index}>{question}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {selectedInsight.actionableSteps.lifestyleChanges && selectedInsight.actionableSteps.lifestyleChanges.length > 0 && (
                    <div className="actionable-subsection">
                      <h4>
                        <span>🔄</span>
                        <span>שינויים באורח החיים:</span>
                      </h4>
                      <ul>
                        {selectedInsight.actionableSteps.lifestyleChanges.map((change, index) => (
                          <li key={index}>{change}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// Simple chart component for insight modal
function SimpleChart({ data, type, color }: { data: any, type: string, color: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvasRef.current || !data?.labels || !data?.datasets) return;
    
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const padding = 60;
    const chartWidth = canvas.width - padding * 2;
    const chartHeight = canvas.height - padding * 2;

    // Clear canvas
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = '#f8f9fa';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Draw axes
    ctx.strokeStyle = '#dee2e6';
    ctx.lineWidth = 1;
    
    // Y axis
    ctx.beginPath();
    ctx.moveTo(padding, padding);
    ctx.lineTo(padding, canvas.height - padding);
    ctx.stroke();

    // X axis
    ctx.beginPath();
    ctx.moveTo(padding, canvas.height - padding);
    ctx.lineTo(canvas.width - padding, canvas.height - padding);
    ctx.stroke();

    // Draw data
    const dataset = data.datasets[0];
    if (!dataset || !dataset.data || dataset.data.length === 0) return;

    if (type === 'line') {
      const maxValue = Math.max(...dataset.data);
      const minValue = Math.min(...dataset.data);
      const valueRange = maxValue - minValue || 1;

      ctx.strokeStyle = color;
      ctx.lineWidth = 3;
      ctx.beginPath();

      dataset.data.forEach((value: number, index: number) => {
        const x = padding + (index / (dataset.data.length - 1)) * chartWidth;
        const y = padding + chartHeight - ((value - minValue) / valueRange) * chartHeight;

        if (index === 0) {
          ctx.moveTo(x, y);
        } else {
          ctx.lineTo(x, y);
        }
      });

      ctx.stroke();

      // Draw points
      ctx.fillStyle = color;
      dataset.data.forEach((value: number, index: number) => {
        const x = padding + (index / (dataset.data.length - 1)) * chartWidth;
        const y = padding + chartHeight - ((value - minValue) / valueRange) * chartHeight;
        
        ctx.beginPath();
        ctx.arc(x, y, 4, 0, 2 * Math.PI);
        ctx.fill();
      });
    }

    // Labels
    ctx.fillStyle = '#6c757d';
    ctx.font = '12px Arial';
    ctx.textAlign = 'center';
    data.labels.forEach((label: string, index: number) => {
      const x = padding + (index / (data.labels.length - 1)) * chartWidth;
      const y = canvas.height - padding + 20;
      ctx.fillText(label, x, y);
    });
  }, [data, type, color]);

  return (
    <canvas 
      ref={canvasRef} 
      width={600} 
      height={300}
      className="simple-chart-canvas"
    />
  );
}
